[toolchain]
channel = "stable"
profile = "default"
components = ["rust-analyzer", "cargo-audit"]
targets = [
    "x86_64-unknown-linux-gnu",
    "i686-unknown-linux-gnu",
    "x86_64-pc-windows-gnu"
]
