["examples:hungry_goblins:ensure_dirs:debug"]
hide = true
run = "mkdir -p examples/hungry_goblins/game/libs/debug/"

["examples:hungry_goblins:ensure_dirs:release"]
hide = true
run = "mkdir -p examples/hungry_goblins/game/libs/release/"

["examples:debug:linux:hungry_goblins"]
hide = true
depends = ["examples:hungry_goblins:ensure_dirs:debug", "build:debug:linux:*"]
description = "Build and deploy libraries for the hungry goblins example for Linux in debug mode"
run = """
  cp target/x86_64-unknown-linux-gnu/debug/libhungry_goblins.d examples/hungry_goblins/game/libs/debug/hungry_goblins.gnu_linux.x86_64.d
  cp target/i686-unknown-linux-gnu/debug/libhungry_goblins.d examples/hungry_goblins/game/libs/debug/hungry_goblins.gnu_linux.x86_32.d
  cp target/x86_64-unknown-linux-gnu/debug/libhungry_goblins.so examples/hungry_goblins/game/libs/debug/hungry_goblins.gnu_linux.x86_64.so
  cp target/i686-unknown-linux-gnu/debug/libhungry_goblins.so examples/hungry_goblins/game/libs/debug/hungry_goblins.gnu_linux.x86_32.so
"""

["examples:release:linux:hungry_goblins"]
hide = true
depends = ["examples:hungry_goblins:ensure_dirs:release", "build:release:linux:*"]
description = "Build and deploy libraries for the hungry goblins example for Linux in release mode"
run = """
  mkdir -p examples/hungry_goblins/game/libs/release/
  cp target/x86_64-unknown-linux-gnu/release/libhungry_goblins.so examples/hungry_goblins/game/libs/release/hungry_goblins.gnu_linux.x86_64.so
  cp target/i686-unknown-linux-gnu/release/libhungry_goblins.so examples/hungry_goblins/game/libs/release/hungry_goblins.gnu_linux.x86_32.so
"""

["examples:debug:windows:hungry_goblins"]
depends = ["examples:hungry_goblins:ensure_dirs:debug", "build:debug:windows:*"]
hide = true
description = "Build and deploy libraries for the hungry goblins example for Windows in debug mode"
run = """
  cp target/x86_64-pc-windows-gnu/debug/hungry_goblins.d examples/hungry_goblins/game/libs/debug/hungry_goblins.win.x86_64.d
  cp target/x86_64-pc-windows-gnu/debug/hungry_goblins.dll examples/hungry_goblins/game/libs/debug/hungry_goblins.win.x86_64.so
"""

["examples:release:windows:hungry_goblins"]
depends = ["examples:hungry_goblins:ensure_dirs:release", "build:release:windows:*"]
hide = true
description = "Build and deploy libraries for the hungry goblins example for Windows in release mode"
run = """
  cp target/x86_64-pc-windows-gnu/release/hungry_goblins.dll examples/hungry_goblins/game/libs/release/hungry_goblins.win.x86_64.dll
"""
