["fmt:rustfmt"]
description = "Format code with rustfmt"
run = "cargo fmt --all -- --config-path {{vars.config_dir}}"

["lint:clippy"]
description = "Lint code with clippy"
run = "cargo clippy --no-deps --all"

["lint:rustfmt"]
description = "Lint code with rustfmt"
run = "cargo fmt --all --check -- --config-path {{vars.config_dir}}"

["fix:clippy"]
description = "Fix code with clippy"
run = "cargo clippy --no-deps --all --fix"

["build:debug:libs"]
description = "Build the project in debug mode"
run = "cross build"

["build:release:libs"]
description = "Build the project in release mode"
run = "cross build --release"

["build:debug:libs:all"]
description = "Build the project in debug mode"
depends = ["build:debug:libs:*"]

["build:release:libs:all"]
description = "Build the project in release mode"
depends = ["build:release:libs:*"]

["build:debug:libs:linux"]
description = "Build the project in debug mode for Linux"
depends = ["build:debug:libs:linux:*"]

["build:debug:libs:windows"]
description = "Build the project in debug mode for Windows"
depends = ["build:debug:libs:windows:*"]

["build:release:libs:linux"]
description = "Build the project in release mode for Linux"
depends = ["build:release:libs:linux:*"]

["build:release:libs:windows"]
description = "Build the project in release mode for Windows"
depends = ["build:release:libs:windows:*"]

["build:debug:libs:linux:32bit"]
description = "Build the project in debug mode for Linux x86_32"
run = "cross build --target i686-unknown-linux-gnu"

["build:debug:libs:linux:64bit"]
description = "Build the project in debug mode for Linux x86_64"
run = "cross build --target x86_64-unknown-linux-gnu"

["build:debug:libs:windows:32bit"]
description = "Build the project in debug mode for Windows x86_32"
run = "cross build --target i686-pc-windows-gnu"

["build:debug:libs:windows:64bit"]
description = "Build the project in debug mode for Windows x64"
run = "cross build --target x86_64-pc-windows-gnu"

["build:release:libs:linux:32bit"]
description = "Build the project in release mode for Linux x86_32"
run = "cross build --release --target i686-unknown-linux-gnu"

["build:release:libs:linux:64bit"]
description = "Build the project in release mode for Linux x86_64"
run = "cross build --release --target x86_64-unknown-linux-gnu"

["build:release:libs:windows:32bit"]
description = "Build the project in release mode for Windows x86_32"
run = "cross build --release --target i686-pc-windows-gnu"

["build:release:libs:windows:64bit"]
description = "Build the project in release mode for Windows x64"
run = "cross build --release --target x86_64-pc-windows-gnu"
